// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPysoZjGaNn4KH8zorKPS99Y4pgxMxo_c',
    appId: '1:455113974699:web:2c52d8942123ad1057a8ee',
    messagingSenderId: '455113974699',
    projectId: 'completefoodorderingappui',
    authDomain: 'completefoodorderingappui.firebaseapp.com',
    storageBucket: 'completefoodorderingappui.firebasestorage.app',
    measurementId: 'G-NPWPRH8PV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoV71MlkWKiinWVqp08Z_PlgsRQjU4r2I',
    appId: '1:455113974699:android:c7b5dbec46adb5b657a8ee',
    messagingSenderId: '455113974699',
    projectId: 'completefoodorderingappui',
    storageBucket: 'completefoodorderingappui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1FZuyzbM_Pw2pcP9_iTQuNmAzSsbp3GE',
    appId: '1:455113974699:ios:e15aca03ba7ef26557a8ee',
    messagingSenderId: '455113974699',
    projectId: 'completefoodorderingappui',
    storageBucket: 'completefoodorderingappui.firebasestorage.app',
    iosBundleId: 'com.example.bakeryadminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1FZuyzbM_Pw2pcP9_iTQuNmAzSsbp3GE',
    appId: '1:455113974699:ios:e15aca03ba7ef26557a8ee',
    messagingSenderId: '455113974699',
    projectId: 'completefoodorderingappui',
    storageBucket: 'completefoodorderingappui.firebasestorage.app',
    iosBundleId: 'com.example.bakeryadminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPysoZjGaNn4KH8zorKPS99Y4pgxMxo_c',
    appId: '1:455113974699:web:e3b74f749798f6dc57a8ee',
    messagingSenderId: '455113974699',
    projectId: 'completefoodorderingappui',
    authDomain: 'completefoodorderingappui.firebaseapp.com',
    storageBucket: 'completefoodorderingappui.firebasestorage.app',
    measurementId: 'G-CTH3WH2ZM8',
  );

}